version: '3'

services:
  bibleapi-graphql:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules/

    # Expose ports [HOST:CONTAINER}
    ports:
      - "3333:3333"

    env_file:
      - .env
